# Generated by Django 5.2.5 on 2025-08-30 00:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('disponible', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField()),
                ('numeroLegal', models.CharField(unique=True)),
                ('telefono', models.CharField(max_length=20)),
                ('correo', models.CharField(max_length=100, unique=True)),
                ('direccion', models.CharField(max_length=255)),
                ('ciudad', models.CharField(max_length=255)),
                ('tipo', models.CharField(choices=[('HF', 'Hostal-familiar'), ('H', 'Hotel'), ('R', 'Restaurante'), ('B', 'Bar'), ('CR', 'Centro recreativo'), ('C', 'Cafetería'), ('TTT', 'Transporte turístico terrestre'), ('OV', 'Operadora de viaje'), ('AV', 'Arrendamiento de Vehículos'), ('CH', 'Casa de Huésped'), ('D', 'Discoteca'), ('CP', 'Canopy'), ('CDN', 'Centro de Diversión Nocturna'), ('AL', 'Albergue')], max_length=3)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('activo', models.BooleanField(default=True)),
                ('administrador', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='proveedor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AlquilerVehiculo',
            fields=[
                ('servicio_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ofertaTuristica.servicio')),
                ('modelo', models.CharField(max_length=255)),
                ('marca', models.CharField(max_length=255)),
            ],
            bases=('ofertaTuristica.servicio',),
        ),
        migrations.CreateModel(
            name='Gastronomico',
            fields=[
                ('servicio_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ofertaTuristica.servicio')),
                ('tipo_comida', models.CharField(choices=[('A', 'Almuerzo'), ('C', 'Cena'), ('D', 'Desayuno'), ('B', 'Bebidas'), ('T', 'Tour gastronómico')], default='A', max_length=50)),
            ],
            bases=('ofertaTuristica.servicio',),
        ),
        migrations.CreateModel(
            name='Habitacion',
            fields=[
                ('servicio_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ofertaTuristica.servicio')),
                ('tipo', models.CharField(choices=[('S', 'single'), ('D', 'double'), ('SU', 'suite')], max_length=2)),
                ('capacidad', models.IntegerField()),
            ],
            bases=('ofertaTuristica.servicio',),
        ),
        migrations.CreateModel(
            name='ViajeDirecto',
            fields=[
                ('servicio_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ofertaTuristica.servicio')),
                ('origen', models.CharField(max_length=255)),
                ('fecha_salida', models.DateTimeField()),
                ('asientos_disponibles', models.IntegerField()),
            ],
            bases=('ofertaTuristica.servicio',),
        ),
        migrations.CreateModel(
            name='Visita',
            fields=[
                ('servicio_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ofertaTuristica.servicio')),
                ('fecha', models.DateTimeField()),
                ('duracion_minutos', models.IntegerField(blank=True, null=True)),
                ('cupo_maximo', models.IntegerField(blank=True, null=True)),
                ('guia_incluido', models.BooleanField(default=True)),
            ],
            bases=('ofertaTuristica.servicio',),
        ),
        migrations.AddField(
            model_name='servicio',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='servicios', to='ofertaTuristica.proveedor'),
        ),
        migrations.CreateModel(
            name='ProveedorImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image_url', models.URLField()),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='ofertaTuristica.proveedor')),
            ],
        ),
        migrations.CreateModel(
            name='ServicioImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('image_url', models.URLField()),
                ('servicio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='ofertaTuristica.servicio')),
            ],
        ),
        migrations.CreateModel(
            name='Destino',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('viaje', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='destinos', to='ofertaTuristica.viajedirecto')),
            ],
        ),
    ]
