# Generated by Django 5.2.5 on 2025-08-30 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='rol',
            field=models.CharField(choices=[('admin', 'Admin'), ('cliente', 'Cliente'), ('operador', 'Operador')], default='cliente', max_length=20),
        ),
    ]
